  
substitutions:
    _SERVICE_NAME: 'si-demo'
    _PROJECT_ID: 'infinity-arc'

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$_PROJECT_ID/$_SERVICE_NAME', '.']
images: ['gcr.io/$_PROJECT_ID/$_SERVICE_NAME']