  
substitutions:
    _SERVICE_NAME: 'si-demo'
    _PROJECT_ID: 'infinity-arc'

steps:
  - name: 'make directory'
    args: ['mkdir','/usr/src/si-demo']
  - name: 'copy auth secrets'
    args: ['cp','gs://infinity-arc_cloudbuild/auth-secret/auth.conf.json','/usr/src/si-demo/auth.conf.json']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$_PROJECT_ID/$_SERVICE_NAME', '.']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', '$_SERVICE_NAME', '--image', 'gcr.io/$_PROJECT_ID/$_SERVICE_NAME', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated','--cpu','1','--memory','128']
  images: ['gcr.io/$_PROJECT_ID/$_SERVICE_NAME']