# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [dev]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Auto-Create-Pull-Request:
    runs-on: ubuntu-latest

    steps:
      - name: auto-create-pr-action
        uses: smartinspereira/auto-create-pr-action@v0.1.0
        env:
          BASE_BRANCH: master
          PULL_REQUEST_DRAFT: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
